groups:
- name: node_common
  interval: 30s
  rules:

  - alert: processor_usage_too_high
    expr: |
      ((sum(node_cpu{mode=~"^(?:^(?:user|nice|system|irq|softirq|steal|idle|iowait)$)$"}) by (instance, job)) - (sum(node_cpu{mode=~"^(?:^(?:idle|iowait)$)$"}) by (instance, job))) / (sum(node_cpu{mode=~"^(?:^(?:user|nice|system|irq|softirq|steal|idle|iowait)$)$"}) by (instance, job)) * 100 > 95
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'Instance {{ $labels.instance }} of job {{ $labels.job }} has processor above 95% (current value: {{ printf "%.2f" $value }}%) for over 5 minutes'
      summary: 'Processor usage above 95%'

  - alert: memory_usage_above_90_percent
    expr: |
      (((node_memory_MemTotal - node_memory_MemFree - node_memory_Cached) / (node_memory_MemTotal) * 100)) > 95
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'Instance {{ $labels.instance }} of job {{ $labels.job }} has memory usage above 90% (current value: {{ printf "%.2f" $value }}%) for over 5 minutes'
      summary: 'Memory usage above 90%'

- name: systemd_unit
  interval: 15s
  rules:

  - alert: systemd_unit_failed
    expr: |
      node_systemd_unit_state{state="failed"} > 0
    for: 3m
    labels:
      severity: critical
    annotations:
      description: 'Instance {{ $labels.instance }}: Service {{ $labels.name }} failed'
      summary: 'Systemd unit failed'

  - alert: systemd_unit_flapping
    expr: |
      changes(node_systemd_unit_state{state="active"}[5m]) > 5 or (changes(node_systemd_unit_state{state="active"}[60m]) > 15 unless changes(node_systemd_unit_state{state="active"}[30m]) < 7)
    labels:
      severity: critical
    annotations:
      description: 'Instance {{ $labels.instance }}: Service {{ $labels.name }} flapping'
      summary: 'Systemd unit flapping'
