---

- name: install prometheus-node-exporter
  pacman: name=prometheus-node-exporter,arch-audit,pacman-contrib state=present

- name: install prometheus-memcached-exporter
  pacman: name=prometheus-memcached-exporter state=present
  when: "'memcached' in group_names"

- name: install node exporter configuration
  template: src=prometheus-node-exporter.env.j2 dest=/etc/conf.d/prometheus-node-exporter owner=root group=root mode=600

- name: create textcollector directory
  file: path="{{ prometheus_textfile_dir }}" state=directory owner=node_exporter group=node_exporter

- name: install node exporter textcollector scripts
  copy: src={{ item }} dest=/usr/local/bin/{{ item }} owner=root group=root mode=0755
  with_items:
    - arch-textcollector.sh
    - borg-textcollector.sh

- name: install arch textcollector service
  template: src=prometheus-arch-textcollector.service.j2 dest=/etc/systemd/system/prometheus-arch-textcollector.service owner=root group=root mode=600

- name: install arch textcollector timer
  template: src=prometheus-arch-textcollector.timer.j2 dest=/etc/systemd/system/prometheus-arch-textcollector.timer owner=root group=root mode=600

- name: enable and start prometheus arch textcollector timer
  systemd: name=prometheus-arch-textcollector.timer enabled=yes daemon_reload=yes state=started

- name: install borg textcollector service
  template: src=prometheus-borg-textcollector.service.j2 dest=/etc/systemd/system/prometheus-borg-textcollector.service owner=root group=root mode=600
  when: "'borg_clients' in group_names"

- name: install borg textcollector timer
  template: src=prometheus-borg-textcollector.timer.j2 dest=/etc/systemd/system/prometheus-borg-textcollector.timer owner=root group=root mode=600
  when: "'borg_clients' in group_names"

- name: enable and start prometheus borg textcollector timer
  systemd: name=prometheus-borg-textcollector.timer enabled=yes daemon_reload=yes state=started
  when: "'borg_clients' in group_names"

- name: enable prometheus-node-exporter service
  systemd: name=prometheus-node-exporter enabled=yes daemon_reload=yes state=started

- name: enable prometheus-memcached-exporter service
  systemd: name=prometheus-memcached-exporter enabled=yes daemon_reload=yes state=started
  when: "'memcached' in group_names"

- name: open prometheus-node-exporter ipv4 port for monitoring.archlinux.org
  firewalld: state=enabled permanent=true immediate=yes
        rich_rule="rule family=ipv4 source address={{ hostvars['monitoring.archlinux.org']['ipv4_address'] }} port protocol=tcp port={{ prometheus_exporter_port }} accept"
  when: "'prometheus' not in group_names"
