---

- name: setup gitlab server
  hosts: gitlab.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: tools }
    - { role: firewalld }
    - { role: sshd }
    - { role: root_ssh }
    - { role: gitlab, gitlab_domain: "gitlab.archlinux.org" }
    - { role: borg-client, tags: ["borg"] }
    - { role: prometheus-exporters }
